### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by yfq512** [liuyuan-pal/NeuRay#25]
感谢作者的分享，我尝试了很多方法，都会报错
```
(py38) root@23504c294479:/cmdata/docker/yfq/NeuRay# python render.py 
Traceback (most recent call last):
  File "render.py", line 12, in <module>
    from network.renderer import name2network
  File "/cmdata/docker/yfq/NeuRay/network/renderer.py", line 13, in <module>
    from network.init_net import name2init_net, DepthInitNet, CostVolumeInitNet
  File "/cmdata/docker/yfq/NeuRay/network/init_net.py", line 5, in <module>
    from inplace_abn import ABN
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/inplace_abn/abn.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/inplace_abn/functions.py", line 8, in <module>
    from . import _backend
ImportError: /opt/conda/envs/py38/lib/python3.8/site-packages/inplace_abn/_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
(py38) root@23504c294479:/cmdata/docker/yfq/NeuRay# 
```
可以帮忙看下么，或者提供完成的python版本,cuda版本，各个三方库的版本；
如果能提供一个可用的docker镜像就再好不过了。

**Comment by liuyuan-pal** [comment]
似乎是inplace_abn这个库出了问题，你可以参考一下这个https://github.com/mapillary/inplace_abn
我的cuda是这边的集群上的，版本是11.0，pytorch是1.7.1

**Comment by yfq512** [comment]
谢谢，是库之间的依赖问题，解决了
