### ISSUE TITLE
渲染自定义数据报错

### ISSUE THREAD

**Issue by yfq512** [liuyuan-pal/NeuRay#26]
我按照文档下载了模型和测试数据，并实际测试了 python render.py dtu数据，是能够生成图像的，但是渲染自定义数据发生报错，（数据仍使用你提供的 desktop 数据，目录结构也是按照文档组织的）
```
python run_colmap.py --example_name desktop --colmap data/example/desktop

Traceback (most recent call last):
  File "run_colmap.py", line 27, in <module>
    process_example_dataset(flags.example_name,flags.same_camera,flags.colmap_path)
  File "/cmdata/docker/yfq/NeuRay/colmap_scripts/process.py", line 38, in process_example_dataset
    db.add_image(img_fn.name, cam_id)
  File "/cmdata/docker/yfq/NeuRay/colmap/database.py", line 181, in add_image
    prior_q[3], prior_t[0], prior_t[1], prior_t[2]))
sqlite3.IntegrityError: UNIQUE constraint failed: images.name
```
能帮忙看下么？万分感谢！

**Comment by YudeWang** [comment]
Hi @yfq512 ,
I get the same error, have you solve it?

**Comment by IncludeMathH** [comment]
+1, I'm troubled with the same error now.
